"""add amount field to Donation

Revision ID: 281b8601a0dd
Revises: e3f539a683a3
Create Date: 2021-02-03 15:32:58.015828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281b8601a0dd'
down_revision = 'e3f539a683a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('amount', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('donations', 'amount')
    # ### end Alembic commands ###
