"""empty message

Revision ID: 634e650e0beb
Revises: 8a00902a5681
Create Date: 2021-01-10 19:29:44.025095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "634e650e0beb"
down_revision = "8a00902a5681"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
