"""empty message

Revision ID: 792b6aec7ea0
Revises: 9caf8b506254
Create Date: 2021-03-06 03:25:54.514886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792b6aec7ea0'
down_revision = '9caf8b506254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_completed')
    # ### end Alembic commands ###
