"""remove unique from Donation.email

Revision ID: 9caf8b506254
Revises: 281b8601a0dd
Create Date: 2021-02-15 13:38:32.956856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9caf8b506254"
down_revision = "281b8601a0dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("donations_email_key", "donations", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("donations_email_key", "donations", ["email"])
    # ### end Alembic commands ###
