name: Client-Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prettier
        uses: creyD/prettier_action@v3.1
        with:
          dry: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
