name: client-lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Install Prettier
        run: npm i -g prettier

      - name: Prettier
        run: prettier --check **/*.ts
